### ISSUE TITLE
Invalid Library

### ISSUE THREAD

**Issue by Ccisneros910** [stephenyeargin/arduino-projects#1]
I downloaded the libraries and I tried to both add them to the Arduino library using the "Add .ZIP library..." option and by adding them manually. When I tried to add them manually, however, the Arduino IDE says they are "Invalid libraries". I installed a set of libraries from Adafruit the same way and they are recognized by the IDE.

The error is the following:
Arduino: 1.8.5 (Windows 10), Board: "Arduino/Genuino Uno"

C:\Users\Karu\Documents\Arduino\MorseTransceiverFinal\MorseTransceiverFinal.ino:8:94: fatal error: Morse.h: No such file or directory

 #include <Morse.h> // libary found at: https://github.com/stephenyeargin/arduino-projects.git

                                                                                              ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by stephenyeargin** [comment]
Howdy! So, this is a pretty old collection of scripts and libraries that I had used to mess with my Arduino unit five years ago. I don't have the board anymore or any of the software, so I'm not sure what may be going on. The `Morese.h` file it is referencing can be found [here](https://github.com/stephenyeargin/arduino-projects/blob/master/libraries/Morse/Morse.h), but I suspect that you may need to move some files around in your project directory to get everything behaving.

[This page](https://charlesreid1.com/wiki/Arduino/Morse_Library) appears to have some of the code I originally included here and may offer some tips for getting it working.
